version: '3.8'

services:
  products-api:
    build: ./products-api-csharp
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  payments-service:
    build: ./payments-service-golang
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  frontend:
    build: ./ecommerce-frontend-angular
    ports:
      - "4200:80"
    depends_on:
      products-api:
        condition: service_healthy
      payments-service:
        condition: service_healthy