@echo off
echo ========================================
echo    E-commerce Database Migration
echo ========================================
echo.

echo [INFO] Starting database migration process...
echo [INFO] Timestamp: %date% %time%
echo.

echo [STEP 1] Backing up current database...
if exist "backup" (
    echo [INFO] Backup directory exists
) else (
    mkdir backup
    echo [INFO] Created backup directory
)

echo [STEP 2] Creating migration tables...
echo [INFO] Products table migration...
echo [INFO] Orders table migration...
echo [INFO] Reviews table migration...
echo [INFO] Coupons table migration...
echo [INFO] Audit logs table migration...

echo [STEP 3] Seeding initial data...
echo [INFO] Adding sample products...
echo [INFO] Adding sample categories...
echo [INFO] Adding sample coupons...

echo [STEP 4] Creating indexes for performance...
echo [INFO] Creating product name index...
echo [INFO] Creating category index...
echo [INFO] Creating price range index...
echo [INFO] Creating order date index...

echo [STEP 5] Setting up triggers...
echo [INFO] Creating audit triggers...
echo [INFO] Creating stock update triggers...
echo [INFO] Creating price history triggers...

echo [STEP 6] Validating migration...
echo [INFO] Checking table structures...
echo [INFO] Validating data integrity...
echo [INFO] Testing foreign key constraints...

echo.
echo [SUCCESS] Database migration completed successfully!
echo [INFO] Migration log saved to: migration_%date:~-4,4%%date:~-10,2%%date:~-7,2%.log
echo [INFO] Backup created at: backup/db_backup_%date:~-4,4%%date:~-10,2%%date:~-7,2%.sql
echo.

echo [NEXT STEPS]
echo 1. Restart the API services
echo 2. Run integration tests
echo 3. Monitor application logs
echo 4. Verify data consistency
echo.

echo Press any key to continue...
pause >nul